version: "3.8"

services:
  db:
       image: postgres
       environment:
           - POSTGRES_DB=postgres
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=postgres

  django:
       build: ./django
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
           - ./django:/app/django
       ports:
           - "8080:8000"
       depends_on:
           - db

  front:
       build: ./front
       volumes: 
          - './front:/app' 
          - '/app/node_modules' 
       environment: 
          - NODE_ENV=development 
          - CHOKIDAR_USEPOLLING=true
       ports:
         - "3000:3000"
       stdin_open: true
       tty: true
